services:
  nextjs:
    container_name: nextjs-website
    build:
      context: .
      dockerfile: containers/Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000"]
      interval: 5s
      retries: 3
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/app
  nginx:
    container_name: nextjs-nginx
    depends_on:
      nextjs:
        condition: service_healthy
    build: 
      context: .
      dockerfile: containers/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"